project:
  type: website
  output-dir: docs # to publish website on GithubPages

website:
  title: "Parma Dash"
  description: "A dashboard for Parma, Italy"
  # favicon: assets/favicon.ico
  
  page-footer:
    left: |
      {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}
      [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) <br> [Luisa M. Mimmi](https://luisamimmi.org/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) <br>
      [Code at {{< fa brands github >}} GitHub](https://github.com/Lulliter/parma-dash)
#      Made with {{< fa brands r-project >}} and ![]({{< var quarto-icon >}}){width=75px} <br> 
    background: "#e3eff7"
  
  # --- Structure of the navbar
  navbar:
    pinned: true
    right:
      - text: Home
        href: index.qmd
      - text: Dashboard
        href: dashboard.qmd
      - text: Data Source
        href: data-source.qmd
      - text: Blog
        href: blog.qmd

format:
  html:
    toc: true
    css: assets/styles/custom.scss
    # theme: cosmo
    # # theme: styles/parma-theme.scss
    # highlight-style: github
    # mainfont: "Lato"
    # monofont: "Fira Mono"
