project:
  type: website
  output-dir: docs # to publish website on GithubPages
  render:
    - "/**/*.qmd"    # tutti i file .qmd (root or subfolders)
    - "!assets/parma_colours.qmd"
    - "!map/**/*.qmd"   # ma NON quelli nella sottocartella map/
    - "!zzz/**/*.qmd"   # e NON uelli cdella sottocartella zzz/

website:
  bread-crumbs: true   
  title: "Parma analisi di contesto"
  description: "A dashboard for Parma, Italy"
  site-url: "https://lulliter.github.io/parma-dash/"
  # favicon: assets/favicon.ico
  
  page-footer:
    left: |
      {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}
      [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) <br> [Luisa M. Mimmi](https://luisamimmi.org/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/) <br>
      [Code at {{< fa brands github >}} GitHub](https://github.com/Lulliter/parma-dash)
#      Made with {{< fa brands r-project >}} and ![]({{< var quarto-icon >}}){width=75px} <br> 
    background: "#E5EBEE"
  
# --- Structure of the navbar
  navbar:
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - text: Dashboard
        href: dashboard.qmd # Qui metterò una sotto pagina per ogni tema 
      - text: Data Source
        href: source.qmd
      - text: Blog
        href: posts.qmd
        
    right:
      - icon: github
        aria-label: github
        href: https://github.com/Lulliter/parma-dash

# --- Structure of the sidebar (if any)
  sidebar:
    - title: "Dashboard"
      style: docked
      background: "#9f7d35"
      contents:
      - dashboard.qmd
      - text: "Tema X"
        href: dashboard/01_tema_x.qmd
      - text: "Tema Y"
        href: dashboard/02_tema_y.qmd  
# 
#       contents:
#         - dashboard.qmd
#         - section: "Tema X"
#           contents:
#             - dashboard/01_tema_x.qmd       
#         - section: "Tema Y"
#           contents:
#             - dashboard/02_tema_y.qmd

# --- Default options for all pages
format:
  html:
    toc: true
    css: assets/styles/custom.scss
    # theme: cosmo
    # # theme: styles/parma-theme.scss
    # highlight-style: github
    # mainfont: "Lato"
    # monofont: "Fira Mono"

# --- Default options for tbl and fig captions location (top)
fig-cap-location: top
tbl-cap-location: top
      
 
      

# --- Important bc Pandoc’s default resource-path is the directory of each input file
# Let pages see files in the project root (.) and the bib folder explicitly
resource-path: [".", "bib"]
#bibliography: bib/CRP_dash.bib
